schema_version = "1.0.0"
id = "Keymap Visualiser"
version = "1.1.0"
name = "Keymap Visualiser"
tagline = "Shows which keymaps are already taken and flgs conflicts"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Keymap-visualizer"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]